### Test the home page endpoint

GET http://localhost:3001/logos

### Test creating a logo after you build the code for adding a logo
POST http://localhost:3001/logos
Content-Type: application/json

{
  "name": "RGB",
  "color": ["purple"],
  "size": "Medium",
  "case": "Upper"
}

### Test the PUT which should change a logo
PUT http://localhost:3001/logos/
Content-Type: application/json

{
  "name": "Super Logo"
}

### Test the DELETE
DELETE http://localhost:3001/logos/5f2c92c697989f2a807c45c4